export const ERestaurantTypes = {
  'Pizzaria': 1,
  'Hamburgueria': 2,
  'Sushi / Japonês': 3,
  'Comida Japonesa': 4,
  'Comida Chinesa': 5,
  'Comida Coreana': 6,
  'Comida Tailandesa': 7,
  'Comida Indiana': 8,
  'Comida Mexicana': 9,
  'Comida Árabe': 10,
  'Comida Mediterrânea': 11,
  'Comida Italiana / Massas': 12,
  'Churrascaria': 13,
  'Carnes': 14,
  'Frutos do Mar': 15,
  'Lanches': 16,
  'Sanduíches': 17,
  'Hot Dog': 18,
  'Tacos / Burritos': 19,
  'Kebab / Shawarma': 20,
  'Comida Caseira': 21,
  'Comida Brasileira': 22,
  'Comida Regional': 23,
  'Vegana': 24,
  'Vegetariana': 25,
  'Saudável / Fitness': 26,
  'Saladas': 27,
  'Padaria': 28,
  'Café / Cafeteria': 29,
  'Açaí': 30,
  'Sorvetes': 31,
  'Sobremesas': 32,
  'Outro': 33,
}

export const PatternEnum = {
  email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  password: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\[\]{};':"\\|,.<>\/?-]).{8,}$/,
  cpf: /^\d{3}\.\d{3}\.\d{3}-\d{2}$/,
  cnpj: /^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/,
  phone: /^\(?\d{2}\)?\s?\d{4,5}-\d{4}$/,
  fullName: /^\s*[A-Za-zÀ-ÖØ-öø-ÿ]+(?:[ '-][A-Za-zÀ-ÖØ-öø-ÿ]+)+\s*$/,
  cityUf: /^[A-Za-zÀ-ÖØ-öø-ÿ\s'-]+\/[A-Za-z]{2}$/,
} as const;
