export interface ICustomer {
    companyName: string,
    cnpj: string,
    businessDays: string,
    businessHoursStart?: string,
    businessHoursEnd?: string,
    restaurantTypeId?: string,
    otherRestaurantType?: string,
    responsibleName: string,
    responsibleCpf: string,
    whatsapp: string,
    email: string,
    passwordHash: string,
    termsAccepted: boolean,
    emailAuthenticate: boolean,
    addressStreet?: string | null,
    addressNumber?: string | null,
    addressComplement?: string | null,
    addressNeighborhood?: string | null,
    addressCity?: string | null,
    addressState?: string | null,
    addressCountry?: string | null,
    addressZipCode?: string | null,
}
